apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: spring-boot-crud-mysql
  name: spring-boot-crud-mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-boot-crud-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-crud-mysql
    spec:
      containers:
        - name: spring-boot-crud-mysql
          image: nikoleye/spring-boot-crud-demo:1.3-MYSQL-KUBE
          imagePullPolicy: IfNotPresent
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
---
# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: spring-boot-crud-mysql
  name: spring-boot-crud-mysql
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080    # Port inside the cluster
      targetPort: 8080   # Port exposed to the outside
  selector:
    app: spring-boot-crud-mysql
  type: NodePort