apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: spring-boot-crud-demo
  name: spring-boot-crud-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-crud-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-boot-crud-demo
    spec:
      containers:
      - image: nikoleye/spring-boot-crud-demo:1.2-H2CONSOLE
        imagePullPolicy: IfNotPresent
        name: spring-boot-crud-demo
        resources:
          requests: 
            cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: spring-boot-crud-demo
  name: spring-boot-crud-demo
  namespace: default
spec:
  ports:
  -  port: 8000
     protocol: TCP
     targetPort: 8000
  selector:
    app: spring-boot-crud-demo
  sessionAffinity: None
  type: LoadBalancer

